"""Cost Display Component for showing LLM usage and costs."""

import streamlit as st
from typing import Dict, Any

def display_cost_metrics(
    cost_data: Dict[str, Any],
    title: str = "AI Processing Costs",
    show_details: bool = True,
    expanded: bool = False
) -> None:
    """
    Display cost metrics in a standardized format.
    
    Args:
        cost_data: Dictionary containing cost information
        title: Title for the cost section
        show_details: Whether to show detailed breakdown
        expanded: Whether to expand the details by default
    """
    if not cost_data or not any([
        cost_data.get('llm_total_cost', 0) > 0,
        cost_data.get('llm_input_tokens', 0) > 0,
        cost_data.get('llm_output_tokens', 0) > 0
    ]):
        st.info("No AI processing costs recorded for this item.")
        return

    # Main cost summary
    total_cost = cost_data.get('llm_total_cost', 0.0)
    input_tokens = cost_data.get('llm_input_tokens', 0)
    output_tokens = cost_data.get('llm_output_tokens', 0)
    model = cost_data.get('llm_model', 'Unknown')
    
    # Display main cost in a prominent way
    if total_cost > 0:
        st.metric(
            label="Total AI Processing Cost",
            value=f"${total_cost:.4f}",
            help="Total cost for LLM API calls during processing"
        )
    
    if show_details:
        with st.expander("Detailed Cost Breakdown", expanded=expanded):
            col1, col2, col3 = st.columns(3)
            
            with col1:
                st.metric(
                    label="Input Tokens",
                    value=f"{input_tokens:,}",
                    help="Tokens sent to the AI model"
                )
            
            with col2:
                st.metric(
                    label="📤 Output Tokens", 
                    value=f"{output_tokens:,}",
                    help="Tokens generated by the AI model"
                )
            
            with col3:
                total_tokens = input_tokens + output_tokens
                st.metric(
                    label="Total Tokens",
                    value=f"{total_tokens:,}",
                    help="Combined input and output tokens"
                )
            
            # Model information
            st.info(f"**Model Used:** {model}")
            
            # Cost per token calculation
            if total_tokens > 0 and total_cost > 0:
                cost_per_token = total_cost / total_tokens * 1000000  # Cost per million tokens
                st.info(f"**Cost per Million Tokens:** ${cost_per_token:.2f}")


def display_cost_comparison(
    cost_data_list: list,
    labels: list,
    title: str = "Cost Comparison"
) -> None:
    """
    Display a comparison of costs across multiple items.
    
    Args:
        cost_data_list: List of cost data dictionaries
        labels: List of labels for each cost data
        title: Title for the comparison section
    """
    st.subheader(title)
    
    if not cost_data_list or len(cost_data_list) != len(labels):
        st.error("Invalid cost data or labels provided.")
        return
    
    # Create comparison table
    comparison_data = []
    for i, (cost_data, label) in enumerate(zip(cost_data_list, labels)):
        total_cost = cost_data.get('llm_total_cost', 0.0)
        input_tokens = cost_data.get('llm_input_tokens', 0)
        output_tokens = cost_data.get('llm_output_tokens', 0)
        model = cost_data.get('llm_model', 'Unknown')
        
        comparison_data.append({
            "Item": label,
            "Total Cost": f"${total_cost:.4f}",
            "Input Tokens": f"{input_tokens:,}",
            "Output Tokens": f"{output_tokens:,}", 
            "Total Tokens": f"{input_tokens + output_tokens:,}",
            "Model": model
        })
    
    # Display as table
    st.table(comparison_data)
    
    # Summary statistics
    total_costs = [data.get('llm_total_cost', 0.0) for data in cost_data_list]
    total_tokens = [data.get('llm_input_tokens', 0) + data.get('llm_output_tokens', 0) for data in cost_data_list]
    
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Total Combined Cost", f"${sum(total_costs):.4f}")
    with col2:
        st.metric("Total Combined Tokens", f"{sum(total_tokens):,}")
    with col3:
        avg_cost = sum(total_costs) / len(total_costs) if total_costs else 0
        st.metric("Average Cost", f"${avg_cost:.4f}")


def display_cost_timeline(
    cost_entries: list,
    title: str = "Cost Timeline"
) -> None:
    """
    Display cost information over time.
    
    Args:
        cost_entries: List of cost entries with timestamps
        title: Title for the timeline section
    """
    st.subheader(title)
    
    if not cost_entries:
        st.info("No cost data available for timeline.")
        return
    
    # Simple timeline display
    for entry in cost_entries:
        timestamp = entry.get('timestamp', 'Unknown')
        cost = entry.get('llm_total_cost', 0.0)
        description = entry.get('description', 'Processing')
        
        st.write(f"**{timestamp}** - {description}: ${cost:.4f}")


def format_cost_summary(cost_data: Dict[str, Any]) -> str:
    """
    Format cost data into a concise summary string.
    
    Args:
        cost_data: Dictionary containing cost information
        
    Returns:
        Formatted cost summary string
    """
    if not cost_data:
        return "No cost data available"
    
    total_cost = cost_data.get('llm_total_cost', 0.0)
    total_tokens = cost_data.get('llm_input_tokens', 0) + cost_data.get('llm_output_tokens', 0)
    model = cost_data.get('llm_model', 'Unknown')
    
    # Always show token count and model, even if cost is 0
    if total_cost > 0 or total_tokens > 0:
        return f"${total_cost:.4f} ({total_tokens:,} tokens, {model})"
    else:
        return "No processing costs"


def get_cost_badge_color(cost: float) -> str:
    """
    Get appropriate color for cost badge based on cost amount.
    
    Args:
        cost: Cost amount
        
    Returns:
        Color string for Streamlit
    """
    if cost == 0:
        return "gray"
    elif cost < 0.01:
        return "green"
    elif cost < 0.05:
        return "orange"
    else:
        return "red"